vich_uploader:
    db_driver: orm
    mappings:
        announce_img:
            uri_prefix: /images/announce_img
            upload_destination: '%kernel.project_dir%/public/images/announce_img'
            namer: vich_uploader.namer_origname

            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true