vich_uploader:
    db_driver: orm
    mappings:
        products:
            uri_prefix: /images/announce
            upload_destination: '%kernel.project_dir%/public/images/announce'
            namer: vich_uploader.namer_origname